name: Push to Docker Hub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image Tag"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          logout: true

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/arm64
          file: ./Dockerfile
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/justlist:${{ github.event.inputs.tag }}
